#!/bin/bash
set -e

wget -qO 'jq-template' 'https://github.com/docker-library/bashbrew/raw/1da7341a79651d28fbcc3d14b9176593c4231942/scripts/jq-template.awk'

bash run-templates "$@"

bash run-builds "$@"

rm -f 'jq-template'