name: Docker Build Target

on:
  workflow_call:
    inputs:
      version:
        description: 'Choose the target version'
        default: '8.3'
        required: true
        type: string

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: checkout repo
        uses: actions/checkout@main
      - name: Build the Docker images
        run: PHP_VERSION=${{ inputs.version }} make build
      - name: Push the Docker images
        run: PHP_VERSION=${{ inputs.version }} make push
      - name: Clean the Docker images
        run: PHP_VERSION=${{ inputs.version }} make clean
