name: Docker CI/CD

on:
  schedule:
    - cron: "0 1 * * 1"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: checkout repo
        uses: actions/checkout@main
      - name: Build the Docker images
        run: make build
      - name: Push the Docker images
        run: make push
      - name: Clean the Docker images
        run: make clean
